### ISSUE TITLE
question (not issue)

### ISSUE THREAD

**Issue by redbox-cdn** [binary-forest/Varnish-Dashboard#3]
Hi 
This is very GOOD dashboard!

I have one question.

is it possible to handles multiple varnish server ? or single server?

Thanks!

**Comment by james-potter** [comment]
It currently only handles one varnish server, although it could be modified to support multiple varnish server.

If you were meaning for things like the VCL deploy or bans to multiple servers etc it would just be a case of creating a list of varnish servers and then iterating over the varnish servers if multiple are chosen as it is just a call to the agent.

For the stats it would be a little more involved as you would have to have the socket to each of the varnish servers and combine the stats from each or you could just create new graphs for each of the servers, I've not really looked into socket.io to multiple servers.

**Comment by redbox-cdn** [comment]
Hi James 

Thank you for the quick reply.

Yes, I would like to provide the adminpanel for endusers.
(change the VCL or apply purge(ban) and get the stats per host(domain name) to multiple servers.)

About VCL, I changed via own bash script to multiple servers.
Purge or ban, I found  the drupal module for varnish(supported multiple site).

But regarding status per domains,  I have no idea. 
So I would like to get the traffic graph per domains at least.
Your program handles via varnishadm? 

In addition, I am not really an expert about node.js and socket.io. I tried your system but doesn't works..
Would you mind let me know way to use this program? I just finished setup below.

1: install nvm form git 
git clone git://github.com/creationix/nvm.git ~/.nvm

2:source ~/.nvm/nvm.sh

3:nvm install 0.10.29

4:create example.js

5:node example.js(works sample program on node.js)

6: download your package from git
git clone https://github.com/binary-forest/Varnish-Dashboard.git

Thanks!

Ashly
